import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <head>
        <script src="https://cdn.jsdelivr.net/npm/eruda" />
        <script dangerouslySetInnerHTML={{ __html: `
          window.onerror = function(m,s,l,c,e) {
            try { eruda.init(); console.error('ERR:'+m+' '+s+':'+l); } catch(x) {}
          };
          window.addEventListener('unhandledrejection', function(e) {
            try { eruda.init(); console.error('PROMISE:'+e.reason); } catch(x) {}
          });
          document.addEventListener('DOMContentLoaded', function() {
            try { eruda.init(); console.log('Eruda OK, DOM ready'); } catch(x) {}
          });
        `}} />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}